// <auto-generated />
using System;
using GestionFutbol.BD.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestionFutbol.BD.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.AsistEntrenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Asistio")
                        .HasColumnType("bit");

                    b.Property<int>("EntrenamientoId")
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EntrenamientoId");

                    b.HasIndex("JugadorId");

                    b.ToTable("AsistEntrenamientos");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.Entrenamiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsistEntrenamientoId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AsistEntrenamientoId");

                    b.ToTable("Entrenamientos");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.EstPartido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Asistencias")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("Goles")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int>("JugadorId")
                        .HasColumnType("int");

                    b.Property<int>("MinutosJugados")
                        .HasMaxLength(3)
                        .HasColumnType("int");

                    b.Property<int>("PartidoId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("EstPartidos");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.Jugador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AsistEntrenamientoId")
                        .HasColumnType("int");

                    b.Property<string>("Edad")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("EstPartidoId")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Posicion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("AsistEntrenamientoId");

                    b.HasIndex("EstPartidoId");

                    b.ToTable("Jugadores");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.Partido", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EstPartidoId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasMaxLength(2)
                        .HasColumnType("datetime2");

                    b.Property<string>("Resultado")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Rival")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("EstPartidoId");

                    b.ToTable("Partidos");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.AsistEntrenamiento", b =>
                {
                    b.HasOne("GestionFutbol.BD.Data.Entity.Entrenamiento", "Entrenamiento")
                        .WithMany()
                        .HasForeignKey("EntrenamientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFutbol.BD.Data.Entity.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entrenamiento");

                    b.Navigation("Jugador");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.Entrenamiento", b =>
                {
                    b.HasOne("GestionFutbol.BD.Data.Entity.AsistEntrenamiento", null)
                        .WithMany("Entrenamientos")
                        .HasForeignKey("AsistEntrenamientoId");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.EstPartido", b =>
                {
                    b.HasOne("GestionFutbol.BD.Data.Entity.Jugador", "Jugador")
                        .WithMany()
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GestionFutbol.BD.Data.Entity.Partido", "Partido")
                        .WithMany()
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.Jugador", b =>
                {
                    b.HasOne("GestionFutbol.BD.Data.Entity.AsistEntrenamiento", null)
                        .WithMany("Jugadores")
                        .HasForeignKey("AsistEntrenamientoId");

                    b.HasOne("GestionFutbol.BD.Data.Entity.EstPartido", null)
                        .WithMany("Jugadores")
                        .HasForeignKey("EstPartidoId");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.Partido", b =>
                {
                    b.HasOne("GestionFutbol.BD.Data.Entity.EstPartido", null)
                        .WithMany("Partidos")
                        .HasForeignKey("EstPartidoId");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.AsistEntrenamiento", b =>
                {
                    b.Navigation("Entrenamientos");

                    b.Navigation("Jugadores");
                });

            modelBuilder.Entity("GestionFutbol.BD.Data.Entity.EstPartido", b =>
                {
                    b.Navigation("Jugadores");

                    b.Navigation("Partidos");
                });
#pragma warning restore 612, 618
        }
    }
}
